name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'style'
      - 'build'
      - 'ci'
      - 'docs'
      - 'test'
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'chore'
      - 'refactor'
      - 'style'
template: |
  ##  What's Changed

  $CHANGES

replacers:
  - search: 'feat\(([^)]+)\):'
    replace: '[$1] '
  - search: 'fix\(([^)]+)\):'
    replace: '[$1] '
  - search: 'chore\(([^)]+)\):'
    replace: '[$1] '
  - search: 'ci\(([^)]+)\):'
    replace: '[$1] '
  - search: 'test\(([^)]+)\):'
    replace: '[$1] '
  - search: 'refactor\(([^)]+)\):'
    replace: '[$1] '
  - search: 'style\(([^)]+)\):'
    replace: '[$1] '
  - search: 'build\(([^)]+)\):'
    replace: '[$1] '
  - search: 'docs\(([^)]+)\):'
    replace: '[$1] '
  - search: 'feat:'
    replace: ''
  - search: 'fix:'
    replace: ''
  - search: 'chore:'
    replace: ''
  - search: 'ci:'
    replace: ''
  - search: 'test:'
    replace: ''
  - search: 'refactor:'
    replace: ''
  - search: 'style:'
    replace: ''
  - search: 'build:'
    replace: ''
  - search: 'docs:'
    replace: ''